name: Build-and-Push-Image
on:
  push:
    branches:
      - main

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    env: 
      REPO_NAME: rishithamarri
      IMAGE_NAME: login-signup-form
      GITHUB_REPO: rishitha1007
      GITOPS_REPO: Gitops-Login-Signup-Form
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "GITHUB_BRANCH= (echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> GITHUB_ENV

      - name: Build-Docker-Image
        run: |
          docker build -t $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB_SHA .

      - name: Push-Image-to-Docker-Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username $REPO_NAME --password-stdin
          docker push $REPO_NAME/$IMAGE_NAME:$GITHUB_REF_NAME-$GITHUB_SHA

      - name: Manifest file
        run: |
          git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/$GITHUB_REPO/$GITOPS_REPO
          cd $GITOPS_REPO
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"
          yq e '.spec.template.spec.containers[0].image = "rishithamarri/login-signup-form:${{ env.GITHUB_BRANCH }}"' -i deployments/deployment.yaml
          git add .
          git commit -m "updating newer image"
          git push --set-upstream origin main\
    
